steps:
  # build the container image  # build the container image
  - name: 'node:${_NODE_VERSION}'
    entrypoint: npm
    args: ['install']
  - name: 'node:${_NODE_VERSION}'
    env:
      - 'APP_ENV=${BRANCH_NAME}'
      - 'PROJECT_ID=${PROJECT_ID}'
      - 'VITE_ENVIRONMENT=${_APP_ENV}'
      - 'VITE_COMMIT_ID=${SHORT_SHA}'
      - 'VERSION=${_VERSION}'
      - 'VITE_POPUP_BASE_URL=${_POPUP_URL}'
    entrypoint: npm
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-h', 'Cache-Control:"Cache-Control:public, max-age=0, must-revalidate"', 'cp', 'dist/assets/crewpass-agency-button-v2.js', 'gs://${PROJECT_ID}-loginbutton/${_APP_NAME}-${_APP_ENV}-${_APP_VERSION}.js']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-h', 'Cache-Control:"Cache-Control:public, max-age=0, must-revalidate"', 'cp', 'dist/assets/crewpass-agency-button-v2.css', 'gs://${PROJECT_ID}-loginbutton/${_APP_NAME}-${_APP_ENV}-${_APP_VERSION}.css']