steps:
  # build the container image  # build the container image
  - name: 'node:${_NODE_VERSION}'
    entrypoint: npm
    args: ['install']
  - name: 'node:${_NODE_VERSION}'
    env:
      - 'APP_ENV=${BRANCH_NAME}'
      - 'PROJECT_ID=${PROJECT_ID}'
      - 'ENVIRONMENT=${_APP_ENV}'
      - 'VERSION=${_VERSION}'
      - 'VITE_POPUP_BASE_URL=${_POPUP_URL}'
    entrypoint: npm
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'dist/assets/index.js', 'gs://${PROJECT_ID}-loginbutton/${_APP_NAME}-${_APP_ENV}-${_APP_VERSION}.js', '--cache-control=no-cache']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'dist/assets/index.css', 'gs://${PROJECT_ID}-loginbutton/${_APP_NAME}-${_APP_ENV}-${_APP_VERSION}.css', '--cache-control=no-cache']